### ISSUE TITLE
Cannot feed value of shape (10000, 784) for Tensor

### ISSUE THREAD

**Issue by zli2014** [maestrojeong/deformable_convnet#1]
Hello, when i run execute 'python main.py', this program shows
 ValueError: Cannot feed value of shape (10000, 784) for Tensor u'Placeholder:0', which has shape '(100, 784)'
 in  "main.py", line 76, in train
this error is cased by config.py

**Comment by jiachen0212** [comment]
you need to modified the main.py, such as:
def train(self):
        create_dir(SAVE_DIR)
        saver = tf.train.Saver(tf.global_variables(), max_to_keep = 10)
        ntrain = len(self.train_data.image)  # traindata : 55000    testdata : 10000
        ntest = len(self.test_data.image)
        nbatch = ntrain//self.batch_size
        nbatch_t = ntest // self.batch_size

        for epoch in range(self.epoch):
            # shuffle start
            index = np.arange(ntrain)
            np.random.shuffle(index)
            shuffle_image = self.train_data.image[index]   # shuffle_image: 55000,784
            shuffle_label = self.train_data.label[index]

            ########################## shuffle the testdata #####################
            index_t = np.arange(ntest)
            np.random.shuffle(index_t)
            shuffle_test = self.test_data.image[index_t]   # shuffle_test: 10000,784
            shuffle_label_t = self.test_data.label[index_t]
            ######################################################################
            # shuffle end

            Train_accuracy = 0
            Test_accuracy = 0
            for batch in tqdm(range(nbatch), ascii = True, desc = "batch"):
                start = self.batch_size*batch
                end = self.batch_size*(batch+1)
                train_feed_dict = {self.image : shuffle_image[start:end], self.label : shuffle_label[start:end]}
                _, batch_accuracy = self.sess.run([self.run_train, self.accuracy], feed_dict = train_feed_dict)
                Train_accuracy += batch_accuracy
            Train_accuracy/=nbatch   # avg acc


            ###################### I modified it .. #########################
            # test_feed_dict = {self.image : self.test_data.image, self.label : self.test_data.label}  #
            for batch in tqdm(range(nbatch_t), ascii = True, desc = "batch"):
                start = self.batch_size*batch
                end = self.batch_size*(batch+1)
                test_feed_dict = {self.image: shuffle_test[start:end], self.label: shuffle_label_t[start:end]}
                test_accuracy = self.sess.run(self.accuracy, feed_dict=test_feed_dict)
                Test_accuracy += test_accuracy
            Test_accuracy/=nbatch_t   # avg test acc

            logger.info("Epoch({}/{}) train_accuracy : {}%, test_accuracy : {}%".format(epoch+1, self.epoch, Train_accuracy, Test_accuracy))
            if epoch%self.save_every == self.save_every-1:
                saver.save(self.sess, os.path.join(SAVE_DIR, 'model'), global_step = epoch+1)


hope it's not too late to you 。。。。

**Comment by zli2014** [comment]
thank u , it run well
